### ISSUE TITLE
[BUG] - Incorrect font sizing on Normal Token Oracle Text.

### ISSUE THREAD

**Issue by bmg50barrett** [MrTeferi/Proxyshop#80]
**Describe the bug**
Normal Tokens are created with incorrect font sizing on Oracle Text.

**To Reproduce**
1. Have manual editing turned on in Proxyshop settings.
2. Render Target with appropriately sized and named image. For this latest bug, I used "Dragon [TARB] {3}.png"
3. Observe Incorrectly sized font in photoshop.

Note: during the steps in photoshop, you can see the font starts out correctly sized. There is a step just before Power and Toughness is added that resizes the text. This occurs when using both mm sizing and pixel sizing.

**Your system:**
 - Python version: 3.11 (64-bit)
 - Windows version: Windows 11 - v10.0.22621
 - Photoshop version: v25.0

**Screenshots**
![image](https://github.com/MrTeferi/Proxyshop/assets/60619372/65a375b1-5bcc-4510-9e71-8b1fafe049d2)

**Comment by bmg50barrett** [comment]
This was also present in Proxyshop v1.11.0 and Photoshop v24.0 as recent as two weeks ago.

**Comment by MrTeferi** [comment]
Issue is not reproducible on Proxyshop v1.12.0 (latest) and with latest token template PSD.

**Comment by MrTeferi** [comment]
Appears this issue has gone stale and seems corrected on the latest Proxyshop in multiple tests so I will close this for now, feel free to comment or re-open if issue still arises on your end with latest Proxyshop
